/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.33
 * Generated at: 2016-03-28 22:51:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"loginForm.css\" />\r\n");
      out.write("<div style=\"min-height:650px;text-align:center;\" class=\"fluid\" id=\"body\">\r\n");
      out.write("      <div class=\"containercenter\">\r\n");
      out.write("        <div id=\"logincontent\">\r\n");
      out.write("          <div id=\"loginform\">\r\n");
      out.write("            <form action=\"Logon\" method=\"post\" id=\"frmLogon\" name=\"frmLogon\">\r\n");
      out.write("              <h2 id=\"FrmH2\">Моята Fibank</h2>\r\n");
      out.write("              <br>\r\n");
      out.write("              <fieldset style=\"font-family: 'Trebuchet MS', arial, sans-serif;\">\r\n");
      out.write("                <table style=\"width: 500px;\">\r\n");
      out.write("                  <tbody><tr>\r\n");
      out.write("                    <td>\r\n");
      out.write("                      <div style=\"padding-left:15px; height:60px\">\r\n");
      out.write("                        <label style=\"text-align:left;\" id=\"l_username\" for=\"UserField\">Потребителско име:<input type=\"text\" class=\"inputi\" value=\"\" name=\"fldUserId\" id=\"UserField\" autocomplete=\"off\">\r\n");
      out.write("                          <span class=\"RequiredData\" id=\"resUserField\">&nbsp;</span>\r\n");
      out.write("                        </label>\r\n");
      out.write("                        <label style=\"text-align:left;\" id=\"l_password\" for=\"PasswordField\">Парола:<input type=\"password\" class=\"inputi\" value=\"\" name=\"fldPassword\" id=\"PasswordField\" autocomplete=\"off\">\r\n");
      out.write("                          <span class=\"RequiredData\" id=\"resPasswordField\">&nbsp;</span>\r\n");
      out.write("                        </label>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td align=\"left\">\r\n");
      out.write("                      <table bgcolor=\"white\" width=\"100%\">\r\n");
      out.write("                        <tbody><tr>\r\n");
      out.write("                          <td style=\"vertical-align:middle; width:80% \">\r\n");
      out.write("                            <table style=\"font-size: 12px; margin-left:35px\">\r\n");
      out.write("                              <tbody><tr>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                  <a title=\"Регистрация на потребител\" id=\"a_reg\" target=\"_self\" href=\"Registration\">Регистрация</a>\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td style=\"padding-left:10px;\">\r\n");
      out.write("                                  <a target=\"_self\" href=\"../LostPassword\" id=\"a_LostPswd\">Забравена парола</a>\r\n");
      out.write("                                </td>\r\n");
      out.write("                              </tr>\r\n");
      out.write("                            </tbody></table>\r\n");
      out.write("                          </td>\r\n");
      out.write("                          <td>\r\n");
      out.write("                            <div style=\"height:28px; margin:10px 0; \">\r\n");
      out.write("                              <input type=\"submit\" value=\"Вход\" class=\"button\">\r\n");
      out.write("                              </a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                          </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                      </tbody></table>\r\n");
      out.write("                    </td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                </tbody></table>\r\n");
      out.write("              </fieldset>\r\n");
      out.write("              <input type=\"hidden\" value=\"Login\" name=\"LoginType\" id=\"LoginType\">\r\n");
      out.write("              <input type=\"hidden\" value=\"bg\" name=\"Lang\" id=\"Lang\">\r\n");
      out.write("            </form>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div style=\"width:100%;\" id=\"SSLInfo\">\r\n");
      out.write("            <table cellspacing=\"0\" cellpadding=\"1\" border=\"0\" align=\"center\" width=\"80\" title=\"Чрез &quot;кликване&quot; можете да се уверите, че този сайт е избрал Thawte SSL за сигурност при електронна търговия и поверителни комуникации.\" id=\"table_thawte\" style=\"margin:0 auto;\">\r\n");
      out.write("              <tbody><tr>\r\n");
      out.write("                <td align=\"center\" width=\"80\" valign=\"top\">\r\n");
      out.write("                  <script src=\"https://seal.thawte.com/getthawteseal?host_name=my.fibank.bg&amp;size=S&amp;lang=en\" type=\"text/javascript\">&nbsp;</script><a target=\"THAWTE_Splash\" onmousedown=\"return v_mDown(event);\" tabindex=\"-1\" href=\"https://sealinfo.thawte.com/thawtesplash?form_file=fdf/thawtesplash.fdf&amp;dn=MY.FIBANK.BG&amp;lang=en\"><img border=\"true\" alt=\"Click to Verify - This site has chosen a thawte SSL Certificate to improve Web site security\" oncontextmenu=\"return false;\" src=\"https://seal.thawte.com/getthawteseal?at=0&amp;sealid=2&amp;dn=MY.FIBANK.BG&amp;lang=en&amp;gmtoff=-180\" name=\"seal\"></a>\r\n");
      out.write("                </td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td align=\"center\" valign=\"top\">\r\n");
      out.write("                  <a style=\"color:#333; text-decoration:none; font:#030303 10px arial,sans-serif; text-align:center; margin:0px; padding:0px;\" target=\"_blank\" href=\"http://www.thawte.com/digital-certificates/\" id=\"a_thawte\" title=\"Информация за SSL сертификатите\">За SSL сертификатите</a>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td width=\"155\">&nbsp;</td>\r\n");
      out.write("              </tr>\r\n");
      out.write("            </tbody></table>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div xmlns=\"\" style=\"text-align:left\" id=\"divwarning\">\r\n");
      out.write("          <br>\r\n");
      out.write("          Уважаеми клиенти,<br><br> Присъединете се към инициативата на Fibank към опазване и спестяване на ограничените природни ресурси. <br><br>\r\n");
      out.write("          Предлагаме Ви да се регистрирате за безплатните електронни извлечения по кредитни карти, предоставени чрез услугата \"Моята Fibank\", при което автоматично ще преустановим изпращането на хартиени извлечения. <br><br>\r\n");
      out.write("          За повече информация: 0700 12 777 или на адрес: <a href=\"mailto: my.fibank@fibank.bg\">my.fibank@fibank.bg</a>\r\n");
      out.write("          <br><br>Разговорите към национален номер 0700 12 777 се таксуват според определените от Вашия оператор цени за обаждане към номера тип 0700 на Vivacom.<br> За абонати на Vivacom обаждане към този номер се таксува като обаждане към стационарен номер в мрежата на Vivacom.\r\n");
      out.write("\r\n");
      out.write("          <br></div>\r\n");
      out.write("          <div xmlns=\"\" style=\"text-align:left\" id=\"message\">\r\n");
      out.write("          ВАЖНО ! <br>ПИБ АД УВЕДОМЯВА КАРТОДЪРЖАТЕЛИТЕ си,  че има информация за получени фалшиви съобщения по електронната поща, които претендират да са изпратени от БОРИКА. С тях се изискват данни на картодържатели, включващи:  име на картодържателя, ПИН код, ЕГН, номер на карта и други лични данни, свързани с картодържателя и картата.\r\n");
      out.write("          <br>Напомняме ви, че банката-издател или БОРИКА по никакъв повод не изискват такива данни. Предупреждаваме картодържателите да не предоставят информация за картите си при никакви обстоятелства, дори ако данните се изискват чрез Интернет сайт, който съдържа логото или наподобява оригиналния сайт на банката или БОРИКА.<br>\r\n");
      out.write("          <br></div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
