-- MySQL Script generated by MySQL Workbench
-- 04/04/16 17:43:32
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema internet_banking
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema internet_banking
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `internet_banking` DEFAULT CHARACTER SET utf8 ;
USE `internet_banking` ;

-- -----------------------------------------------------
-- Table `internet_banking`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `internet_banking`.`users` (
  `id` VARCHAR(10) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `type` ENUM('admin', 'business', 'citizen') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `internet_banking`.`login_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `internet_banking`.`login_history` (
  `id_login_history` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `id_of_user_who_logged_in` VARCHAR(10) NOT NULL,
  `ip` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_login_history`),
  INDEX `id_of_user_who_logged_in_idx` (`id_of_user_who_logged_in` ASC),
  CONSTRAINT `id_of_user_who_logged_in`
    FOREIGN KEY (`id_of_user_who_logged_in`)
    REFERENCES `internet_banking`.`users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `internet_banking`.`bank_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `internet_banking`.`bank_products` (
  `id_bank_product` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `interest` DOUBLE NOT NULL,
  `min_sum` DOUBLE NOT NULL,
  `period_in_months` INT NOT NULL,
  PRIMARY KEY (`id_bank_product`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `internet_banking`.`accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `internet_banking`.`accounts` (
  `iban` CHAR(22) NOT NULL,
  `balance` DOUBLE NOT NULL,
  `currency` VARCHAR(10) NOT NULL,
  `account_holder` VARCHAR(10) NOT NULL,
  `date_of_creation` DATE NOT NULL,
  `type` INT NOT NULL,
  PRIMARY KEY (`iban`),
  INDEX `type_idx` (`type` ASC),
  INDEX `account_holder_idx` (`account_holder` ASC),
  CONSTRAINT `type`
    FOREIGN KEY (`type`)
    REFERENCES `internet_banking`.`bank_products` (`id_bank_product`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `account_holder`
    FOREIGN KEY (`account_holder`)
    REFERENCES `internet_banking`.`users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `internet_banking`.`transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `internet_banking`.`transactions` (
  `id_transaction` INT NOT NULL AUTO_INCREMENT,
  `sender_iban` CHAR(22) NOT NULL,
  `receiver_iban` CHAR(22) NOT NULL,
  `currency` VARCHAR(10) NOT NULL,
  `ip_of_sender` VARCHAR(30) NOT NULL,
  `sum` DOUBLE NOT NULL,
  PRIMARY KEY (`id_transaction`),
  INDEX `sender_idx` (`sender_iban` ASC),
  INDEX `receiver_iban_idx` (`receiver_iban` ASC),
  CONSTRAINT `sender_iban`
    FOREIGN KEY (`sender_iban`)
    REFERENCES `internet_banking`.`accounts` (`iban`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `receiver_iban`
    FOREIGN KEY (`receiver_iban`)
    REFERENCES `internet_banking`.`accounts` (`iban`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
